version: "3.8"

services:
  nextjs_app_staging:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs_app_staging
    environment:
      - NODE_ENV=staging
    ports:
      - "3001:3000" # possible error, check if different port is fine
    restart: unless-stopped #only restart when stopping manually
