name: Deploy Staging Before Production

on:
  push:
    branches:
      - staging # staging branch in repo

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH and Start Staging
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DIGITALOCEAN_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/mywebsite/frontend
            sudo docker-compose -f docker-compose.override.yml up -d --build
