name: Deploy updates via DO VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Connect to VPS & Pull Code
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DIGITALOCEAN_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # pull new changes from main branch
            cd ~/mywebsite/frontend
            git pull origin main

            # stop old image and remove it
            docker stop nextjs_app || true
            docker rm nextjs_app || true

            # build new image and run it
            docker build -t mywebsite:latest .
            docker run -d --name nextjs_app -p 3000:3000 mywebsite:latest

            # get rid of old resources
            docker image prune -f
            docker volume prune -f

